# This is a basic workflow to help you get started with Actions

name: EC2 auto deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  pull:
    runs-on: ubuntu-latest
    steps:
      #IP取得ライブラリをインストール
      - name: Public IP Install
        id: ip
        uses: haythem/public-ip@v1.2
       
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #deploy
      - name: Pull
        run: |
         # SSH接続して、git pullする
         echo "${{ secrets.GIT_PRIVATE_KEY }}" > private_key
         chmod 600 private_key
         ssh -oStrictHostKeyChecking=no ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST_NAME }} -i private_key "cd ~/Blockory && git fetch --prune && git checkout main && git pull origin main"
         
  build:
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: build
        run: |
          ssh -oStrictHostKeyChecking=no ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST_NAME }} -i private_key "cd ~/Blockory/backend/src/build && bash build.sh"
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        run: |
          ssh -oStrictHostKeyChecking=no ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST_NAME }} -i private_key "sudo systemctl restart Blockory.service"
  
  
  
  
  
  
